const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const nav=$('.nav'), menu=$('.menu'), links=$('.navlinks');
addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>24),{passive:true});
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));links.classList.toggle('open',!open)});
$$('.navlinks a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
 const steps=$$('.steps article'), method=$('.method-progress');const mo=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const n=steps.indexOf(e.target)+1;method?.style.setProperty('--method',`${n*20}%`)}}),{rootMargin:'-35% 0px -45%'});steps.forEach(s=>mo.observe(s));
}else $$('.reveal').forEach(el=>el.classList.add('visible'));
$$('[data-product]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.product;$$('[data-product]').forEach(b=>b.setAttribute('aria-selected',String(b===btn)));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===key));$('.product-stage').dataset.stage=key}));
const fmt=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function calculate(){const form=$('#impact-form');if(!form)return;const d=Object.fromEntries(new FormData(form));const units=+d.units,staff=+d.staff,hours=+d.hours,cost=+d.cost,processes=+d.processes,losses=+d.losses;const factor=Math.min(.3,.15+processes*.005);const hoursLow=Math.round(hours*52*factor),hoursHigh=Math.round(hours*52*Math.min(.4,factor+.1));const adminLow=hoursLow*cost,adminHigh=hoursHigh*cost;const lossLow=losses*12*.05,lossHigh=losses*12*.15;$('#saved-hours').textContent=`${hoursLow.toLocaleString('pt-BR')}–${hoursHigh.toLocaleString('pt-BR')} h/ano`;$('#admin-saving').textContent=`${fmt.format(adminLow)}–${fmt.format(adminHigh)}`;$('#loss-saving').textContent=`${fmt.format(lossLow)}–${fmt.format(lossHigh)}`;$('#impact-range').textContent=`${fmt.format(adminLow+lossLow)}–${fmt.format(adminHigh+lossHigh)}`;const vals={units,staff,hours:`${hours}h`,cost:fmt.format(cost),processes,losses:fmt.format(losses)};Object.entries(vals).forEach(([k,v])=>{const o=$(`output[for="${k}"]`);if(o)o.textContent=v})}
$('#impact-form')?.addEventListener('input',calculate);calculate();
